<?$APPLICATION->IncludeComponent("bitrix:news.list", "footer_social", 
	array(
		"IBLOCK_TYPE" => "content",
		"IBLOCK_ID" => "#ELASTO_BLOCK_SOCIAL_IBLOCK_ID#",
		"NEWS_COUNT" => "10",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ACTIVE_FROM",
		"SORT_ORDER2" => "DESC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(),
		"PROPERTY_CODE" => array(
			0 => "ICON",
			1 => "BACKGR_HOV",
			2 => "URL"
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "",
		"AJAX_OPTION_SHADOW" => "",
		"AJAX_OPTION_JUMP" => "",
		"AJAX_OPTION_STYLE" => "",
		"AJAX_OPTION_HISTORY" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_FILTER" => "",
		"CACHE_GROUPS" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "",
		"DISPLAY_PANEL" => "",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "",
		"HIDE_LINK_WHEN_NO_DETAIL" => "",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"DISPLAY_NAME" => "",
		"DISPLAY_DATE" => "",
		"DISPLAY_TOP_PAGER" => "",
		"DISPLAY_BOTTOM_PAGER" => "",
		"PAGER_SHOW_ALWAYS" => "",
		"PAGER_TEMPLATE" => "",
		"PAGER_DESC_NUMBERING" => "",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "",
		"PAGER_SHOW_ALL" => "",
		"AJAX_OPTION_ADDITIONAL" => ""
	),
	false
);?>